version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - seu_volume_local:/var/lib/postgresql/data

volumes:
  seu_volume_local: